version: '3'
services:
  gddev-website:
    container_name: gddev-website
    build:
      context: .
      dockerfile:
        Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production