name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-output.outputs.artifact_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        id: build
        run: |
          yarn install
          yarn build

      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Artifact to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
