name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-output.outputs.artifact_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: gddev-website-artifact
          path: dist

  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Artifact to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: gddev-website-artifact
