name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-output.outputs.artifact_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build
        id: build
        run: |
          yarn install
          yarn build

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup upload Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
