name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.2.2
        with:
          artifact_name: gddev-site-artifact
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: gddev-site-artifact
