name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          yarn install --frozen-lockfile
          yarn build

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup upload Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache
        id: yarn-cache
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: ./
          depth: 5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gary-dickenson.github.io
