name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: {{ steps.set-output.outputs.artifact_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          artifact_name: gddev-site-artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: gddev-site-artifact
