name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install and Build
      run: |
        yarn install
        yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        EXTERNAL_REPOSITORY: gary-dickenson/gary-dickenson.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: dist
